name: esp32_bluetooth_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^10.2.0
  cupertino_icons: ^1.0.8
  flutter_radial_gauge: ^0.0.4
  gauge_indicator: ^0.4.3
  url_launcher: ^6.3.0
  share_plus: ^10.0.2
  # syncfusion_flutter_gauges: ^19.3.57

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/temperature.png
    - assets/gasoline.png
    - assets/ethanol.png
