name: esp32_bluetooth_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^10.2.0
  cupertino_icons: ^1.0.8
  flutter_radial_gauge: ^0.0.4
  flutter_launcher_icons: ^0.12.0
  gauge_indicator: ^0.4.3
  url_launcher: ^6.3.0
  share_plus: ^10.0.2
  provider: ^6.0.5
  percent_indicator: ^4.2.2
  intl: ^0.18.0
  printing: ^5.12.1  # Para imprimir ou compartilhar o PDF

  # syncfusion_flutter_gauges: ^19.3.57

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter_icons:
  android: true
  ios: false
  image_path: "assets/xerloquinho.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/temperature.png
    - assets/combustivel.png
    - assets/battery.png
    - assets/logo-start.png
    - assets/xerloq.png
    - assets/xerloquinho.png